apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gallowhead-prod-cert
  namespace: gallowhead
spec:
  secretName: gallowhead-prod-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - gallowhead.com
    - www.gallowhead.com