name: Deploy Nginx Reverse Proxy Config

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false

jobs:

  deploy-nginx:
    name: Deploy Nginx Reverse Proxy Config
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Nginx
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "deploy/webserver/proxy/test.gallowhead.com.conf"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/etc/nginx/sites-enabled/"
          EXCLUDE: "/dist/, /node_modules/"
          SCRIPT_BEFORE: |
            ls -al
          SCRIPT_AFTER: |
            ln -s /etc/nginx/sites-available/test.gallowhead.com.conf /etc/nginx/sites-enabled/ && nginx -t