name: Pull latest Docker image and start container
# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  workflow_run:
      workflows: ['Create and publish a Docker image']
      types: [completed]
      branches:
          - 'main'
env:
  REGISTRY: ghcr.io

jobs:

  deploy-compose:
    name: Deploy compose
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key:  ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        source: "deploy/app/docker-compose.yml"
        target: /var/data/services/test-gallowhead/

  start-container:
    needs: deploy-compose
    name: Start container and cleanup
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
    - name: Checks, moving docker-compose.yml, start container
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          if [ ! -d /var/data/services/test-gallowhead ]; then \ 
            mkdir /var/data/services/test-gallowhead \ 
          fi
          mv /var/data/services/test-gallowhead/deploy/app/docker-compose.yml /var/data/services/test-gallowhead/docker-compose.yml && rm -rf /var/data/services/test-gallowhead/deploy && \ 
          cd /var/data/services/test-gallowhead/ && \ 
          docker login ${{ env.REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} && \ 
          docker compose up --build -d && \
          docker logout
