name: Deploy Nginx Reverse Proxy Config

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false

jobs:

  deploy-nginx:
    name: Deploy Nginx Reverse Proxy Config
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key:  ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        source: "deploy/webserver/proxy/test.gallowhead.com.conf"
        target: /etc/nginx/sites-available/

  check-config:
    needs: deploy-nginx
    name: Move config, cleanup copy dir and check config
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          chown root: /etc/nginx/sites-available/deploy/webserver/proxy/test.gallowhead.com.conf && \ 
          mv /etc/nginx/sites-available/deploy/webserver/proxy/test.gallowhead.com.conf /etc/nginx/sites-available/test.gallowhead.com.conf && \ 
          rm -rf /etc/nginx/sites-available/deploy && \ 
          ln -s /etc/nginx/sites-available/test.gallowhead.com.conf /etc/nginx/sites-enabled/ && \ 
          nginx -t
