name: Pull latest Docker image and start container
# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  workflow_run:
      workflows: ['Create and publish a Docker image']
      types: [completed]
      branches:
          - 'main'

jobs:

  deploy-compose:
    name: Deploy compose
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key:  ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        source: "deploy/app/docker-compose.yml"
        target: /var/data/services/test-gallowhead/

  start-container:
    name: Start container and cleanup
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          if [ ! -d /var/data/services/test-gallowhead ]; then
            mkdir /var/data/services/test-gallowhead
          fi
          
          cd /var/data/services/test-gallowhead && \ 
          mv /var/data/services/test-gallowhead/deploy/app/docker-compose.yml . && rm -rf deploy/app && docker compose up --build -d
