name: Pull latest Docker image and start container
# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  workflow_run:
      workflows: ['Semantic release, create and publish a Docker image']
      types: [completed]
      branches:
          - 'main'
env:
  REGISTRY: ghcr.io

jobs:

  start-container:
    name: Start container and cleanup
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
    - name: Checks, moving docker-compose.yml, start container
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          docker login ${{ env.REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} && \ 
          docker pull ghcr.io/muchasxmaracas/gallowhead:1.0.0 && \
          docker run -d -p 127.0.0.1:12442:8081 --name test-gallowhead ghcr.io/muchasxmaracas/gallowhead:1.0.0 && \
          docker logout
