name: Docker Image Build Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file prod.Dockerfile --tag gallowhead:prod-$(date +%s)
