name: "Semantic Release"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4.0.2
        with:
          cache: npm
          node-version: lts/*
      - uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: true
          ci: true
          branches: |
            [
              {
                name: 'main',
              }
            ]
          extra_plugins: |
            semantic-release/changelog@6.0.3
            semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
